"""Embed assets/operator.png into inc/operator_png_data.h as a byte array.

Overlay used to file-read this at runtime; that required the launcher to
copy assets/ into the cage next to the decrypted overlay. Embedding the
image in the PE removes that dependency — the overlay is now self-contained.

Usage: python scripts/embed_operator_png.py
"""
from __future__ import annotations
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC  = ROOT / "assets" / "operator.png"
DST  = ROOT / "inc" / "operator_png_data.h"


def main() -> int:
    if not SRC.exists():
        print(f"[!] missing {SRC}", file=sys.stderr); return 1
    data = SRC.read_bytes()

    lines = ["// AUTO-GENERATED by scripts/embed_operator_png.py — do not hand-edit.",
             "// Regenerate: python scripts/embed_operator_png.py",
             "#pragma once",
             "#include <stddef.h>",
             "#include <stdint.h>",
             "",
             f"// {SRC.name}: {len(data):,} bytes",
             "static const uint8_t OPERATOR_PNG_DATA[] = {"]

    # 16 bytes per line, hex format
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        row = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {row},")

    lines.append("};")
    lines.append(f"static const size_t OPERATOR_PNG_SIZE = sizeof(OPERATOR_PNG_DATA);")
    lines.append("")

    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"[+] wrote {DST} ({len(data):,} B PNG -> {DST.stat().st_size:,} B header)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
